### ISSUE TITLE
[Bug]: Failing to read AWS S3 file(s)

### ISSUE THREAD

**Issue by arindamchoudhury** [ray-project/ray-educational-materials#88]
### Notebook with bug

https://github.com/ray-project/ray-educational-materials/blob/main/Introductory_modules/Introduction_to_Ray_AI_Runtime.ipynb

### What happened?

Failed to execute following python code:

```python
# Read Parquet file to Ray Dataset.
dataset = ray.data.read_parquet(
    "s3://anyscale-training-data/intro-to-ray-air/nyc_taxi_2021.parquet"
)




### Environment info



Python version: 3.11.3
Ray version: 2.5.0



### Issue Severity

High: It blocks me from completing my task.

**Comment by kamil-kaczmarek** [comment]
@arindamchoudhury can you please post error msg?

**Comment by arindamchoudhury** [comment]
here it is:
```
---------------------------------------------------------------------------
RayTaskError(OSError)                     Traceback (most recent call last)
Cell In[3], line 2
      1 # Read Parquet file to Ray Dataset.
----> 2 dataset = ray.data.read_parquet(
      3     "s3://anyscale-training-data/intro-to-ray-air/nyc_taxi_2021.parquet"
      4 )

File [~/.local/lib/python3.11/site-packages/ray/data/read_api.py:605](https://file+.vscode-resource.vscode-cdn.net/home/arindam/Projects/personal/ray-educational-materials/Introductory_modules/~/.local/lib/python3.11/site-packages/ray/data/read_api.py:605), in read_parquet(paths, filesystem, columns, parallelism, ray_remote_args, tensor_column_schema, meta_provider, **arrow_parquet_args)
    544 """Create an Arrow dataset from parquet files.
    545 
    546 Examples:
   (...)
    599     Dataset producing Arrow records read from the specified paths.
    600 """
    601 arrow_parquet_args = _resolve_parquet_args(
    602     tensor_column_schema,
    603     **arrow_parquet_args,
    604 )
--> 605 return read_datasource(
    606     ParquetDatasource(),
    607     parallelism=parallelism,
    608     paths=paths,
    609     filesystem=filesystem,
    610     columns=columns,
    611     ray_remote_args=ray_remote_args,
    612     meta_provider=meta_provider,
    613     **arrow_parquet_args,
    614 )

File [~/.local/lib/python3.11/site-packages/ray/_private/auto_init_hook.py:18](https://file+.vscode-resource.vscode-cdn.net/home/arindam/Projects/personal/ray-educational-materials/Introductory_modules/~/.local/lib/python3.11/site-packages/ray/_private/auto_init_hook.py:18), in wrap_auto_init..auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File [~/.local/lib/python3.11/site-packages/ray/data/read_api.py:380](https://file+.vscode-resource.vscode-cdn.net/home/arindam/Projects/personal/ray-educational-materials/Introductory_modules/~/.local/lib/python3.11/site-packages/ray/data/read_api.py:380), in read_datasource(datasource, parallelism, ray_remote_args, **read_args)
    372     scheduling_strategy = NodeAffinitySchedulingStrategy(
    373         ray.get_runtime_context().get_node_id(),
    374         soft=False,
    375     )
    376     get_read_tasks = cached_remote_fn(
    377         _get_read_tasks, retry_exceptions=False, num_cpus=0
    378     ).options(scheduling_strategy=scheduling_strategy)
--> 380     requested_parallelism, min_safe_parallelism, read_tasks = ray.get(
    381         get_read_tasks.remote(
    382             datasource,
    383             ctx,
    384             cur_pg,
    385             parallelism,
    386             local_uri,
    387             _wrap_arrow_serialization_workaround(read_args),
    388         )
    389     )
    391 if read_tasks and len(read_tasks) < min_safe_parallelism * 0.7:
    392     perc = 1 + round((min_safe_parallelism - len(read_tasks)) [/](https://file+.vscode-resource.vscode-cdn.net/) len(read_tasks), 1)

File [~/.local/lib/python3.11/site-packages/ray/_private/auto_init_hook.py:18](https://file+.vscode-resource.vscode-cdn.net/home/arindam/Projects/personal/ray-educational-materials/Introductory_modules/~/.local/lib/python3.11/site-packages/ray/_private/auto_init_hook.py:18), in wrap_auto_init..auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File [~/.local/lib/python3.11/site-packages/ray/_private/client_mode_hook.py:103](https://file+.vscode-resource.vscode-cdn.net/home/arindam/Projects/personal/ray-educational-materials/Introductory_modules/~/.local/lib/python3.11/site-packages/ray/_private/client_mode_hook.py:103), in client_mode_hook..wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File [~/.local/lib/python3.11/site-packages/ray/_private/worker.py:2540](https://file+.vscode-resource.vscode-cdn.net/home/arindam/Projects/personal/ray-educational-materials/Introductory_modules/~/.local/lib/python3.11/site-packages/ray/_private/worker.py:2540), in get(object_refs, timeout)
   2538     worker.core_worker.dump_object_store_memory_usage()
   2539 if isinstance(value, RayTaskError):
-> 2540     raise value.as_instanceof_cause()
   2541 else:
   2542     raise value

RayTaskError(OSError): ray::_get_read_tasks() (pid=5449, ip=192.168.1.147)
            ^^^^^^^^^^^^^^^^^^
  File "/home/arindam/.local/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 1776, in __new__
    return _ParquetDatasetV2(
           ^^^^^^^^^^^^^^^^^^
  File "/home/arindam/.local/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2465, in __init__
    finfo = filesystem.get_file_info(path_or_paths)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_fs.pyx", line 571, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: When getting information for key 'intro-to-ray-air/nyc_taxi_2021.parquet' in bucket 'anyscale-training-data': AWS Error UNKNOWN (HTTP status 400) during HeadObject operation: No response body.

During handling of the above exception, another exception occurred:

ray::_get_read_tasks() (pid=5449, ip=192.168.1.147)
  File "/home/arindam/.local/lib/python3.11/site-packages/ray/data/read_api.py", line 1968, in _get_read_tasks
    reader = ds.create_reader(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arindam/.local/lib/python3.11/site-packages/ray/data/datasource/parquet_datasource.py", line 170, in create_reader
    return _ParquetDatasourceReader(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arindam/.local/lib/python3.11/site-packages/ray/data/datasource/parquet_datasource.py", line 211, in __init__
    _handle_read_os_error(e, paths)
  File "/home/arindam/.local/lib/python3.11/site-packages/ray/data/datasource/file_meta_provider.py", line 358, in _handle_read_os_error
    raise OSError(
OSError: Failing to read AWS S3 file(s): "anyscale-training-data/intro-to-ray-air/nyc_taxi_2021.parquet". Please check that file exists and has properly configured access. You can also run AWS CLI command to get more detailed error message (e.g., aws s3 ls ). See https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html and https://docs.ray.io/en/latest/data/creating-datasets.html#reading-from-remote-storage for more information.
```

**Comment by kamil-kaczmarek** [comment]
@arindamchoudhury how did you solve it?

**Comment by arindamchoudhury** [comment]
hi,

I am using [aws-google-auth](https://pypi.org/project/aws-google-auth/) for work purposes and it has 8 hour authentication expiration.

When I tried to run the ray related code, the authentication was expired.

As the link is public, I thought it should not matter. but it was the reason for the error.
